spring.application.name=Projekatsiit2023

spring.datasource.url=jdbc:postgresql://ep-floral-thunder-ag03xfda-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_R1H9EvfuPVWa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

